import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider,SignIn} from "@clerk/nextjs";
import {
 
  SignedIn,
  SignedOut,
  
} from '@clerk/nextjs';
import NavBar from "@/components/NavBar";
import { Outfit } from "next/font/google";

const inter=Outfit({subsets:['latin']})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SignedIn>
          <NavBar/>
           {children}
        </SignedIn>
        <SignedOut>
            <SignIn/>
        </SignedOut>
      </body>
    </html>
    </ClerkProvider>
  );
}
